#pragma once

#include <juce_audio_processors/juce_audio_processors.h>
#include <SamplerEngine.h>                 // from dehli_musikk_sampler_engine
#include <audio/EmbeddedFlacSource.h>
#include <model/ManifestLoader.h>          // brings Manifest.h (dm::PresetLibrary)
#include <memory>

/** Omni-84 plugin processor.

    M2: loads the embedded JSON manifest + FLAC bundle (generated by
    ds-plugin-converter) into the sampler engine, so the current mode (Bass) is
    audible. Modes/FX/parameters/UI grow in later milestones — see ../../PLAN.md.
*/
class Omni84AudioProcessor : public juce::AudioProcessor
{
public:
    Omni84AudioProcessor();
    ~Omni84AudioProcessor() override;

    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;
    bool isBusesLayoutSupported (const BusesLayout& layouts) const override;
    void processBlock (juce::AudioBuffer<float>&, juce::MidiBuffer&) override;

    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override { return true; }

    const juce::String getName() const override { return JucePlugin_Name; }

    bool acceptsMidi() const override  { return true; }
    bool producesMidi() const override { return false; }
    bool isMidiEffect() const override { return false; }
    double getTailLengthSeconds() const override { return 0.0; }

    int getNumPrograms() override            { return 1; }
    int getCurrentProgram() override         { return 0; }
    void setCurrentProgram (int) override    {}
    const juce::String getProgramName (int) override { return {}; }
    void changeProgramName (int, const juce::String&) override {}

    void getStateInformation (juce::MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;

    dm::SamplerEngine& getEngine() noexcept { return engine; }

    /** On-screen keyboard state — lets the Standalone be played without external
        MIDI gear (the editor shows a MidiKeyboardComponent bound to it). */
    juce::MidiKeyboardState& getKeyboardState() noexcept { return keyboardState; }

    /** Name of the embedded mode currently loaded (empty if none). */
    juce::String getLoadedModeName() const;

private:
    /** Decode the embedded manifest + FLAC bundle into the engine's sample source
        and keep the parsed library alive. No-op if no assets were embedded. */
    void loadEmbeddedLibrary();

    dm::SamplerEngine engine;
    juce::MidiKeyboardState keyboardState;

    std::unique_ptr<dm::EmbeddedFlacSource> sampleSource;
    dm::PresetLibrary library;     // kept alive: the engine's zones reference its source
    bool loaded { false };

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (Omni84AudioProcessor)
};
