#pragma once

#include <juce_audio_processors/juce_audio_processors.h>
#include <SamplerEngine.h>                 // from dehli_musikk_sampler_engine
#include <audio/EmbeddedFlacSource.h>
#include <model/ManifestLoader.h>          // brings Manifest.h (dm::PresetLibrary)
#include <params/ManifestParameters.h>   // shared param machinery (engine)
#include <ui/ManifestEditor.h>            // reusable editor + ManifestEditorHost (engine)
#include <atomic>
#include <functional>
#include <memory>

/** Omni-84 plugin processor.

    M5: loads the embedded JSON manifest + FLAC bundle (generated by
    ds-plugin-converter) into the sampler engine and exposes a mode switcher across
    all of the library's modes. Data-driven UI + parameters arrive in M4 —
    see ../../PLAN.md.
*/
class Omni84AudioProcessor : public juce::AudioProcessor,
                             public  dm::ManifestEditorHost,
                             private juce::AudioProcessorValueTreeState::Listener,
                             private juce::AsyncUpdater
{
public:
    Omni84AudioProcessor();
    ~Omni84AudioProcessor() override;

    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;
    bool isBusesLayoutSupported (const BusesLayout& layouts) const override;
    void processBlock (juce::AudioBuffer<float>&, juce::MidiBuffer&) override;

    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override { return true; }

    const juce::String getName() const override { return JucePlugin_Name; }

    bool acceptsMidi() const override  { return true; }
    bool producesMidi() const override { return false; }
    bool isMidiEffect() const override { return false; }
    double getTailLengthSeconds() const override { return 0.0; }

    int getNumPrograms() override            { return 1; }
    int getCurrentProgram() override         { return 0; }
    void setCurrentProgram (int) override    {}
    const juce::String getProgramName (int) override { return {}; }
    void changeProgramName (int, const juce::String&) override {}

    void getStateInformation (juce::MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;

    dm::SamplerEngine& getEngine() noexcept { return engine; }
    bool isLoaded() const noexcept          { return loaded; }

    // --- dm::ManifestEditorHost (drives the reusable editor) -------------------
    juce::AudioProcessorValueTreeState& getApvts() override            { return *apvts; }
    juce::MidiKeyboardState& getKeyboardState() override               { return keyboardState; }
    juce::StringArray getModeNames() const override                    { return engine.getModeNames(); }
    int  getActiveModeIndex() const override                           { return engine.getActiveModeIndex(); }
    void setPitchWheel (int value14) override { uiPitchWheel.store (value14); }  // 0..16383, centre 8192
    void setModWheel   (int value7)  override { uiModWheel.store (value7);  }    // CC1, 0..127
    juce::Image loadImage (const juce::String& id) override;                     // BinaryData (see .cpp)

    /** The active mode (for the renderer + binding interpreter), or nullptr. */
    const dm::Mode* getActiveMode() const override
    {
        if (! loaded) return nullptr;
        const int i = engine.getActiveModeIndex();
        if (i < 0 || i >= library.modes.size()) return nullptr;
        return &library.modes.getReference (i);
    }

private:
    /** Decode the embedded manifest + FLAC bundle into the engine's sample source
        and hand the library to the engine. No-op if no assets were embedded. */
    void loadEmbeddedLibrary();

    // Mode is a parameter; switching builds a render unit (allocates), so the
    // actual switch is deferred to the message thread via AsyncUpdater.
    void parameterChanged (const juce::String& paramID, float newValue) override;
    void handleAsyncUpdate() override;

    // Declared before the engine so they outlive it: the engine's per-mode render
    // units hold pointers into `library` and `sampleSource`.
    juce::MidiKeyboardState keyboardState;
    std::unique_ptr<dm::EmbeddedFlacSource> sampleSource;
    dm::PresetLibrary library;
    bool loaded { false };

    dm::SamplerEngine engine;

    // Built after the library loads (defaults are read from the manifest).
    std::unique_ptr<juce::AudioProcessorValueTreeState> apvts;

    // Pending on-screen wheel values (-1 = nothing to send this block).
    std::atomic<int> uiPitchWheel { -1 };
    std::atomic<int> uiModWheel   { -1 };

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (Omni84AudioProcessor)
};
