#pragma once

#include <juce_audio_processors/juce_audio_processors.h>
#include <SamplerEngine.h>                 // from dehli_musikk_sampler_engine
#include <audio/EmbeddedFlacSource.h>
#include <model/ManifestLoader.h>          // brings Manifest.h (dm::PresetLibrary)
#include "Parameters.h"
#include <functional>
#include <memory>

/** Omni-84 plugin processor.

    M5: loads the embedded JSON manifest + FLAC bundle (generated by
    ds-plugin-converter) into the sampler engine and exposes a mode switcher across
    all of the library's modes. Data-driven UI + parameters arrive in M4 —
    see ../../PLAN.md.
*/
class Omni84AudioProcessor : public juce::AudioProcessor,
                             private juce::AudioProcessorValueTreeState::Listener,
                             private juce::AsyncUpdater
{
public:
    Omni84AudioProcessor();
    ~Omni84AudioProcessor() override;

    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;
    bool isBusesLayoutSupported (const BusesLayout& layouts) const override;
    void processBlock (juce::AudioBuffer<float>&, juce::MidiBuffer&) override;

    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override { return true; }

    const juce::String getName() const override { return JucePlugin_Name; }

    bool acceptsMidi() const override  { return true; }
    bool producesMidi() const override { return false; }
    bool isMidiEffect() const override { return false; }
    double getTailLengthSeconds() const override { return 0.0; }

    int getNumPrograms() override            { return 1; }
    int getCurrentProgram() override         { return 0; }
    void setCurrentProgram (int) override    {}
    const juce::String getProgramName (int) override { return {}; }
    void changeProgramName (int, const juce::String&) override {}

    void getStateInformation (juce::MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;

    dm::SamplerEngine& getEngine() noexcept { return engine; }

    /** The plugin's automatable parameters (named union across modes). */
    juce::AudioProcessorValueTreeState& getApvts() noexcept { return *apvts; }

    /** Invoked on the message thread after the active mode actually changes (from
        the editor selector, host automation, or state restore) so the editor can
        rebuild its face. Set by the editor; cleared in its destructor. */
    std::function<void()> onModeChanged;

    /** On-screen keyboard state — lets the Standalone be played without external
        MIDI gear (the editor shows a MidiKeyboardComponent bound to it). */
    juce::MidiKeyboardState& getKeyboardState() noexcept { return keyboardState; }

    // Mode switcher (for the editor's selector).
    juce::StringArray getModeNames() const     { return engine.getModeNames(); }
    int  getActiveModeIndex() const             { return engine.getActiveModeIndex(); }
    void setActiveMode (int index)              { engine.setActiveMode (index); }
    bool isLoaded() const noexcept              { return loaded; }

    /** The active mode (for the renderer + binding interpreter), or nullptr. */
    const dm::Mode* getActiveMode() const
    {
        if (! loaded) return nullptr;
        const int i = engine.getActiveModeIndex();
        if (i < 0 || i >= library.modes.size()) return nullptr;
        return &library.modes.getReference (i);
    }

    /** The active mode's UI tree (for the data-driven renderer), or nullptr. */
    const dm::Ui* getActiveModeUi() const
    {
        if (auto* m = getActiveMode()) return &m->ui;
        return nullptr;
    }

private:
    /** Decode the embedded manifest + FLAC bundle into the engine's sample source
        and hand the library to the engine. No-op if no assets were embedded. */
    void loadEmbeddedLibrary();

    // Mode is a parameter; switching builds a render unit (allocates), so the
    // actual switch is deferred to the message thread via AsyncUpdater.
    void parameterChanged (const juce::String& paramID, float newValue) override;
    void handleAsyncUpdate() override;

    // Declared before the engine so they outlive it: the engine's per-mode render
    // units hold pointers into `library` and `sampleSource`.
    juce::MidiKeyboardState keyboardState;
    std::unique_ptr<dm::EmbeddedFlacSource> sampleSource;
    dm::PresetLibrary library;
    bool loaded { false };

    dm::SamplerEngine engine;

    // Built after the library loads (defaults are read from the manifest).
    std::unique_ptr<juce::AudioProcessorValueTreeState> apvts;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (Omni84AudioProcessor)
};
